### ISSUE TITLE
Klipper Configuration Optimization

### ISSUE THREAD

**Issue by nomadsgalaxy** [Positron3D/PositronConfig#2] opened 2024-10-05 20:10 UTC

**Comment by smiksky** [comment] 2024-10-08 07:44
The goal of The Optimizatiopalooza is not to significantly change the way the Positron worked, but to clean up, organize, and optimize the configuration files and their layout making them easier to navigate and edit.

Here's a quick overview of the changes:
- All three macro files have now been combined into `positron_macros.cfg`, and all the stepper settings for sensorless homing tuning are now in `printer.cfg`
- `CHOME` and `G29` have been depreciated in favor of Marlin–style `G28 O` for an 'optional' homing command. `G28 X Z O` or any other combination of axis will also work should you need them
- `[bed_tilt]` is no longer enabled, as we stopped recommending it in favor of manual leveling even before we swithed to the Z-endstop
- KlipperScreen can now be updated from Fluidd or KlipperScreen
- The Buzzer and LED color are no longer listed on Fluidd or KlipperScreen for user control, opting to keep the LEDs as status indicator and avoid having the buzzer left on indefinately
- Adopt the Fluidd (and Mainsail) provided macros for `PAUSE`, `RESUME`, and `CANCEL`

**Comment by smiksky** [comment] 2024-10-08 07:49
This should've been set up as a PR rather than an issue, but we're still figuring out how we're going to use GitHub in our development workflow, so the only issue here is that we're still learning how to GitHub

**Comment by smiksky** [comment] 2024-10-08 07:55
Closed as a duplicate of #3

**Closed as not planned by smiksky** 2024-10-08 07:55 UTC
Labels: enhancement, invalid
